apiVersion: v1
kind: Namespace
metadata:
  name: opencode-web
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencode-workspace
  namespace: opencode-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencode-data
  namespace: opencode-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencode-web
  namespace: opencode-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencode-web
  template:
    metadata:
      labels:
        app: opencode-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: opencode-web
        image: opencode-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "5003"
        - name: OPENCODE_SERVER_PORT
          value: "5551"
        - name: DATABASE_PATH
          value: "/app/data/opencode.db"
        - name: WORKSPACE_PATH
          value: "/workspace"
        - name: PROCESS_START_WAIT_MS
          value: "2000"
        - name: PROCESS_VERIFY_WAIT_MS
          value: "1000"
        - name: HEALTH_CHECK_INTERVAL_MS
          value: "5000"
        - name: HEALTH_CHECK_TIMEOUT_MS
          value: "30000"
        - name: MAX_FILE_SIZE_MB
          value: "50"
        - name: MAX_UPLOAD_SIZE_MB
          value: "50"
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: data
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5003
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5003
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: opencode-workspace
      - name: data
        persistentVolumeClaim:
          claimName: opencode-data
---
apiVersion: v1
kind: Service
metadata:
  name: opencode-web
  namespace: opencode-web
spec:
  type: ClusterIP
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: opencode-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencode-web
  namespace: opencode-web
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: opencode.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: opencode-web
            port:
              number: 5003
